language: node_js
node_js:
- node
cache: yarn
install:
- npm install --global --upgrade yarn
- yarn install
jobs:
  include:
  - stage: Lint
    if: type = push
    script:
    - yarn outdated
    - yarn tsc
    - yarn ts-node source/cli.ts
  - stage: Release
    if: type = api
    script:
    - yarn ts-node source/cli.ts --compile
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
  - stage: Deploy
    if: tag IS present
    script:
    - yarn tsc
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$" ]] ; then export NPM_TAG="next" ; fi
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$" ]] ; then export NPM_TAG="latest" ; fi
    deploy:
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: $NPM_TAG
        on:
          tags: true
